# 机器人信息
std_msgs/Header header
string model     # 机器人型号
string name      # 机器人名称
string description          # 描述
string serial_number        # 序列号
string production_date      # 出厂日期
string hardware_version     # 硬件版本
string software_version     # 软件版本
string software_release_time    # 软件发布时间
string software_release_info    # 软件发布信息，待定，可能是URL
string os_version               # 操作系统版本
string os_release_time          # 操作系统发布时间
string os_release_info          # 操作系统发布日志
string controller_version       # 主控软件版本
string controller_release_time   # 主控软件发布时间
string controller_release_info   # 主控软件发布日志